Fixes to fdstart script (symlink handling, default handling) and made fdstop default to fdstopall when it doesn't have any arguments

diff --git a/etc/fdstart.in b/etc/fdstart.in
--- a/etc/fdstart.in
+++ b/etc/fdstart.in
@@ -1,7 +1,11 @@
 #!/bin/sh
-TARGETS=$1
-shift
+DEFAULT_TARGETS="@config_dir@/daemons @config_dir@/servlets"
+TARGETS=""
+while ((test $# -ne "0") && ((test -d $1) || (test -f $1)));
+   do TARGETS="${TARGETS} $1"; shift; 
+done
 XARGS=$*
+if test "x${TARGETS}" = "x"; then TARGETS=${DEFAULT_TARGETS}; fi
 export FD_LOGLEVEL=7
 export FD_LAUNCHER=${FD_LANUCHER:-fdstart} 
 export LAUNCHCFG="LAUNCHER=${FD_LAUNCHER}" 
@@ -9,16 +13,13 @@ export COMMONCFG="RESTART=1 PIDWAIT=no STEALSOCKETS=yes"
 export FDSTART="sudo -u @fdaemon@ -g @admin_group@"
 export WEBSTART="sudo -u @webuser@ -g @admin_group@"
 for TARGET in ${TARGETS}; do
-    export SERVLETCFG="${COMMONCFG} STATEDIR=@servlet_rundir@ FDSTART=${TARGET}";
     export DAEMONCFG="${LAUNCHCFG} ${COMMONCFG} STATEDIR=@daemon_rundir@ FDSTART=${TARGET}";
     for ctl in $(find -L ${TARGET} -name "*.fdz");
-    do if (readlink ${ctl}>/dev/null);
-       then echo "Starting daemon manager for ${ctl}";
-	    ${FDSTART} LOGFILE=@daemon_logdir@/`basename ${ctl} .fdz`.log \
-		       fdserver `readlink ${ctl}` ${DAEMONCFG} ${XARGS};
-       else echo "Starting daemon manager for ${ctl}";
-	    ${FDSTART} LOGFILE=@daemon_logdir@`basename ${ctl} .fdz`.log \
-		       fdserver ${ctl} ${DAEMONCFG} ${XARGS}; 
+    do echo "Starting daemon manager for ${ctl}";
+       if (readlink -e ${ctl}>/dev/null);
+       then ${FDSTART} LOGFILE=@daemon_logdir@/`basename ${ctl} .fdz`.log \
+	        fdserver `readlink -e ${ctl}` ${DAEMONCFG} ${XARGS};
+       else echo "Missing daemon controller " ${ctl} " linked to " `readlink -m ${ctl}`;
        fi;
     done;
 done;
@@ -26,51 +27,39 @@ for TARGET in ${TARGETS}; do
     export SERVLETCFG="${COMMONCFG} STATEDIR=@servlet_rundir@ FDSTART=${TARGET}";
     export DAEMONCFG="${LAUNCHCFG} ${COMMONCFG} STATEDIR=@daemon_rundir@ FDSTART=${TARGET}";
     for sock in $(find -L ${TARGET} -name "*.sock");
-    do if (readlink ${sock}>/dev/null);
+    do if (readlink -e ${sock}>/dev/null);
        then @SUDO@ touch @servlet_rundir@/`basename ${sock}`.nospawn;
 	    echo "Starting servlet manager for ${sock}";
 	    ${WEBSTART} LOGFILE=@servlet_logdir@/`basename ${sock} .sock`.log \
-			fdservlet @servlet_rundir@/`basename ${sock}` ${LAUNCHCFG} \
-			CONFIG=`readlink ${sock}` ${SERVLETCFG} ${XARGS};
-       else @SUDO@ touch @servlet_rundir@/`basename ${sock}`.nospawn;
-	    echo "Starting servlet manager for ${sock}";
-	    ${WEBSTART} LOGFILE=@servlet_logdir@/`basename ${sock} .sock`.log      \
-			fdservlet @servlet_rundir@/`basename ${sock}` ${LAUNCHCFG} \
-			CONFIG=${sock} ${SERVLETCFG} ${XARGS};
+		 fdservlet @servlet_rundir@/`basename ${sock}` ${LAUNCHCFG} \
+		 CONFIG=`readlink -e ${sock}` ${SERVLETCFG} ${XARGS};
+       else echo "Missing servlet controller " ${sock} " linked to " `readlink -m ${sock}`;
        fi;
     done;
 done;
 for TARGET in ${TARGETS}; do
     export SERVLETCFG="${COMMONCFG} STATEDIR=@servlet_rundir@ FDSTART=${TARGET}";
-    export DAEMONCFG="${LAUNCHCFG} ${COMMONCFG} STATEDIR=@daemon_rundir@ FDSTART=${TARGET}";
     for cfg in $(find -L ${TARGET} -name "*.cfg");
-    do if (readlink ${cfg}>/dev/null);
-       then @SUDO@ touch @servlet_rundir@/`basename ${cfg} .cfg`.sock.nospawn;
-	    echo "Starting servlet manager for ${cfg}";
+    do if (readlink -e ${cfg}>/dev/null);
+       then @SUDO@ touch @servlet_rundir@/`basename ${cfg} .cfg`.nospawn;
+	    echo "Starting servlet manager using ${cfg}";
 	    ${WEBSTART} LOGFILE=@servlet_logdir@/`basename ${cfg} .cfg`.log \
-			fdservlet @servlet_rundir@/`basename ${cfg} .cfg`.sock \
-			${LAUNCHCFG} CONFIG=`readlink ${cfg}` ${SERVLETCFG} ${XARGS};
-       else @SUDO@ touch @servlet_rundir@/`basename ${sock} .cfg`.sock.nospawn;
-	    echo "Starting servlet manager for ${cfg}";
-	    ${WEBSTART} LOGFILE=@servlet_logdir@/`basename ${cfg} .cfg`.log \
-			fdservlet @servlet_rundir@/`basename ${cfg} .cfg`.sock \
-			${LAUNCHCFG} CONFIG=${cfg} ${SERVLETCFG} ${XARGS};
+		 fdservlet @servlet_rundir@/`basename ${cfg} .cfg` ${LAUNCHCFG} \
+		 CONFIG=`readlink -e ${cfg}` ${SERVLETCFG} ${XARGS};
+       else echo "Missing servlet controller " ${cfg} " linked to missing " `readlink -m ${cfg}`;
        fi;
     done;
 done;
 for TARGET in ${TARGETS}; do
     export SERVLETCFG="${COMMONCFG} STATEDIR=@servlet_rundir@ FDSTART=${TARGET}";
-    export DAEMONCFG="${LAUNCHCFG} ${COMMONCFG} STATEDIR=@daemon_rundir@ FDSTART=${TARGET}";
     for addr in $(find -L ${TARGET} -name "*@*");
-    do if (readlink ${addr}>/dev/null);
-       then echo "Starting servlet manager for ${addr}";
-	    ${WEBSTART} LOGFILE=@servlet_logdir@/${addr}.log \
-			fdservlet `basename ${addr}` CONFIG=`readlink ${addr}` \
-			${LAUNCHCFG} ${SERVLETCFG} ${XARGS};
-       else echo "Starting servlet manager for ${addr}";
-	    ${WEBSTART} LOGFILE=@servlet_logdir@/${addr}.log   \
-			fdservlet `basename ${addr}` CONFIG=${addr} \
-			${LAUNCHCFG} ${SERVLETCFG} ${XARGS};
+    do if (readlink -e ${addr}>/dev/null);
+       then @SUDO@ touch @servlet_rundir@/`basename ${addr}`.nospawn;
+	    echo "Starting servlet manager using ${addr}";
+	    ${WEBSTART} LOGFILE=@servlet_logdir@/`basename ${addr}`.log \
+		 fdservlet @servlet_rundir@/`basename ${addr}` ${LAUNCHCFG} \
+		 CONFIG=`readlink -e ${addr}` ${SERVLETCFG} ${XARGS};
+       else echo "Missing servlet controller " ${addr} " linked to missing " `readlink -m ${addr}`;
        fi;
     done;
 done;
